name: news_pojo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts :
  easy_localization :
  http :
  bloc :
  flutter_bloc :
  flutter_screenutil :
  dio :
  flutter_gen :
  hive :
  hive_flutter :
  url_launcher :
  json_annotation:
  cached_network_image: 3.4.1

flutter_gen:
  output: lib/core/resources/
  assets:
    enabled: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:
  json_serializable:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/dark/
    - assets/images/light/
    - assets/icons/
    - assets/logos/
    - assets/translations/