name: news_pojo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts :
  http :
  bloc :
  flutter_bloc :
  flutter_svg :
  flutter_screenutil :
  fluttertoast :
  dio :
  easy_localization :
  flutter_gen :
  hive :
  hive_flutter :
  url_launcher :


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
